harvester/docker-machine-driver-harvester

go.mod
go.sum
vendor/github.com/harvester/go-harvester/pkg/client/auth.go
vendor/github.com/harvester/go-harvester/pkg/clientbase/client.go
vendor/github.com/harvester/go-harvester/pkg/errors/errors.go
vendor/modules.txt

Retry on error

---

go.mod
go.sum
harvester/create.go
vendor/github.com/harvester/go-harvester/pkg/builder/disk.go
vendor/modules.txt

Add image id

---

harvester/create.go

support harvester v0.1.0-xxx

---

go.mod
go.sum
harvester/create.go
vendor/github.com/harvester/go-harvester/pkg/builder/vm.go
vendor/modules.txt

Add pod anti affinity

---

.github/workflows/release.yml

Add s3 upload action

---

harvester/create.go

use default namespace for ssh-key

---

harvester/harvester.go

1. change kill to stop  (only cli use kill)
2. wait vm stoped (only cli use stop)
3. wait vm removed
4. foreground delete

Wait state sync

---

.github/workflows/release.yml

Update gh action

---

harvester/flags.go
harvester/harvester.go

Add cluster type for ui

---

harvester/client.go
harvester/harvester.go

Fix virtualmachine volume delete

---

go.mod
go.sum
harvester/create.go

**Related issues**
https://github.com/harvester/harvester/issues/1455

Bump rancher machine and set pvc hotpluggable to false

---

Dockerfile.dapper

Signed-off-by: Zespre Chang <zespre.chang@suse.com>
harvester/harvester#3149

build(image): stick with mirror version

---

harvester/config.go
harvester/config_test.go

Signed-off-by: futuretea <Hang.Yu@suse.com>
**Related issues**
https://github.com/harvester/harvester/issues/2426

DHCP not always generate a default route

---

.github/workflows/codeql.yml
.github/workflows/release.yml
.github/workflows/scan.yml
.golangci.yml
Dockerfile.dapper

- add codeql for vulnerability scanning.
- add trivy scanning for security enhancement.

Add codeql and trivy scanning

---

scripts/build
scripts/package

PR changes ci to build and package amd64 and arm64 based artifacts.
Related to: https://github.com/harvester/harvester/issues/6053

build and package multi-arch artifacts

---

Dockerfile.dapper
go.mod

https://github.com/harvester/harvester/issues/6160

feat: upgrade go version to 1.22

---

Dockerfile.dapper
go.mod

https://github.com/harvester/harvester/issues/7336

feat: bump go to v1.23

---

harvester/create.go

Add a label with just the node pool name.
Set the machine set name label in all cases
related-to: harvester/harvester#8391
The Harvester node driver for Rancher adds a label with the cluster name to VMs, which belong to a cluster in Rancher.
It also adds a label with the name of the node pool the VM belongs to, but for some reason it only does so when an (anti-) affinity is set.
The Harvester node driver should add the machine pool label in all cases to enable the load balancer to select the VMs for the backends more granularly.
For easier handling it also adds a label the consists of just the node pool name alone. This is in contrast to the machine set label, which also contains the namespace and cluster name and if the label gets too long is hashed.
harvester/harvester8391
SURE-9641

set node pool label

---

harvester/create.go
harvester/flags.go
harvester/harvester.go

Add reserved memory field to docker-machine-driver-harvester.
https://github.com/harvester/harvester/issues/5764

feat: add reserved memory field

---

.golangci.yml
Dockerfile.dapper
harvester/client.go
harvester/cloudinit.go
harvester/create.go
harvester/harvester.go

https://github.com/harvester/harvester/issues/8749

feat: upgrade golangci-lint to latest
